development:
  adapter: postgresql
  database: family_development
  encoding: unicode
  username: devuser
  password: devuser
  host: localhost

test:
  adapter: postgresql
  database: family_test
  encoding: unicode
  username: devuser
  password: devuser
  host: localhost